version: "3.9"
services:
  codemate-connect-db:
    image: postgres
    restart: always
    container_name: codemate-connect-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
